const SALES_COLUMN_MAP = {
    A: 'sale_id',
    B: 'sale_date',
    C: 'state',
    D: 'status_description',
    E: 'multi_product_package',
    F: 'belongs_to_kit',
    G: 'units',
    H: 'product_revenue',
    I: 'price_increase_revenue',
    J: 'installment_fee',
    K: 'sales_fee_and_taxes',
    L: 'shipping_revenue',
    M: 'shipping_fees',
    N: 'refunds',
    O: 'total_amount',
    P: 'billing_month',
    Q: 'ads_sale',
    R: 'sku',
    S: 'listing_id',
    T: 'sales_channel',
    U: 'listing_title',
    V: 'variation',
    W: 'unit_price',
    X: 'listing_type',
    Y: 'nfe_attached',
    Z: 'personal_or_company_data',
    AA: 'document_type_number',
    AB: 'address',
    AC: 'taxpayer_type',
    AD: 'state_registration',
    AE: 'buyer_name',
    AF: 'business',
    AG: 'cpf',
    AH: 'buyer_address',
    AI: 'city',
    AJ: 'buyer_state',
    AK: 'postal_code',
    AL: 'country',
    AM: 'delivery_method',
    AN: 'delivery_shipped_date',
    AO: 'delivery_delivered_date',
    AP: 'delivery_driver',
    AQ: 'delivery_tracking_number',
    AR: 'delivery_tracking_url',
    AS: 'return_units',
    AT: 'return_method',
    AU: 'return_shipped_date',
    AV: 'return_delivered_date',
    AW: 'return_driver',
    AX: 'return_tracking_number',
    AY: 'return_tracking_url',
    AZ: 'reviewed_by_ml',
    BA: 'review_date',
    BB: 'money_released',
    BC: 'result',
    BD: 'destination',
    BE: 'result_reason',
    BF: 'complaint_units',
    BG: 'complaint_opened',
    BH: 'complaint_closed',
    BI: 'mediation'
};

const SALES_TRANSFORMS = {
    sale_date: 'date',
    units: 'number',
    product_revenue: 'currency',
    price_increase_revenue: 'currency',
    installment_fee: 'currency',
    sales_fee_and_taxes: 'currency',
    shipping_revenue: 'currency',
    shipping_fees: 'currency',
    refunds: 'currency',
    total_amount: 'currency',
    unit_price: 'currency',
    delivery_shipped_date: 'date',
    delivery_delivered_date: 'date',
    return_units: 'number',
    return_shipped_date: 'date',
    return_delivered_date: 'date',
    review_date: 'date',
    money_released: 'currency',
    complaint_units: 'number',
    sku: 'string',
    listing_id: 'string',
    buyer_name: 'string',
    cpf: 'string',
    buyer_address: 'string',
    city: 'string',
    buyer_state: 'string',
    postal_code: 'string',
    country: 'string',
    delivery_method: 'string',
    status_description: 'string',
    listing_title: 'string',
    state: 'string'
};

const SALES_CONFIG = {
    collection: 'sales',
    uniqueField: 'sale_id',
    startRow: 6
};

module.exports = {
    SALES_COLUMN_MAP,
    SALES_TRANSFORMS,
    SALES_CONFIG
};